name: main

on:
  pull_request:
  push:
    branches: [main]

jobs:
  main:
    uses: asottile/workflows/.github/workflows/tox.yml@adfec6a1ccb5d6b189aa153676d4f0743afa21c1 # v1.11.0
    with:
      env: '["py314"]'
  main-win:
    uses: asottile/workflows/.github/workflows/tox.yml@adfec6a1ccb5d6b189aa153676d4f0743afa21c1 # v1.11.0
    with:
      env: '["py314"]'
      os: windows-latest
