name: release

on:
  push:
    tags:
    - '**'

permissions: {}

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    uses: mxr/workflows/.github/workflows/github-release.yml@4d2a6bd2164c4dd6b9cedf67fe61be03377e5e95 # v0.1.1
    permissions:
      contents: write
